// This file is generated by server/scripts/generate-embedded-web-assets.ts.
// Do not edit by hand.

import asset0 from '../../../web/dist/apple-touch-icon-180x180.png' assert { type: 'file' };
import asset1 from '../../../web/dist/assets/c-BIGW1oBm.js' assert { type: 'file' };
import asset2 from '../../../web/dist/assets/csharp-K5feNrxe.js' assert { type: 'file' };
import asset3 from '../../../web/dist/assets/css-DPfMkruS.js' assert { type: 'file' };
import asset4 from '../../../web/dist/assets/diff-D97Zzqfu.js' assert { type: 'file' };
import asset5 from '../../../web/dist/assets/dockerfile-BcOcwvcX.js' assert { type: 'file' };
import asset6 from '../../../web/dist/assets/github-dark-DHJKELXO.js' assert { type: 'file' };
import asset7 from '../../../web/dist/assets/github-light-DAi9KRSo.js' assert { type: 'file' };
import asset8 from '../../../web/dist/assets/go-Dn2_MT6a.js' assert { type: 'file' };
import asset9 from '../../../web/dist/assets/graphql-ChdNCCLP.js' assert { type: 'file' };
import asset10 from '../../../web/dist/assets/html-GMplVEZG.js' assert { type: 'file' };
import asset11 from '../../../web/dist/assets/index-CSldWD4Q.js' assert { type: 'file' };
import asset12 from '../../../web/dist/assets/index-CxSTaK8w.css' assert { type: 'file' };
import asset13 from '../../../web/dist/assets/ini-BEwlwnbL.js' assert { type: 'file' };
import asset14 from '../../../web/dist/assets/java-CylS5w8V.js' assert { type: 'file' };
import asset15 from '../../../web/dist/assets/javascript-wDzz0qaB.js' assert { type: 'file' };
import asset16 from '../../../web/dist/assets/json-Cp-IABpG.js' assert { type: 'file' };
import asset17 from '../../../web/dist/assets/jsx-g9-lgVsj.js' assert { type: 'file' };
import asset18 from '../../../web/dist/assets/kotlin-BdnUsdx6.js' assert { type: 'file' };
import asset19 from '../../../web/dist/assets/make-CHLpvVh8.js' assert { type: 'file' };
import asset20 from '../../../web/dist/assets/markdown-Cvjx9yec.js' assert { type: 'file' };
import asset21 from '../../../web/dist/assets/php-CDn_0X-4.js' assert { type: 'file' };
import asset22 from '../../../web/dist/assets/powershell-Dpen1YoG.js' assert { type: 'file' };
import asset23 from '../../../web/dist/assets/python-B6aJPvgy.js' assert { type: 'file' };
import asset24 from '../../../web/dist/assets/rust-B1yitclQ.js' assert { type: 'file' };
import asset25 from '../../../web/dist/assets/scss-OYdSNvt2.js' assert { type: 'file' };
import asset26 from '../../../web/dist/assets/shellscript-Yzrsuije.js' assert { type: 'file' };
import asset27 from '../../../web/dist/assets/sql-BLtJtn59.js' assert { type: 'file' };
import asset28 from '../../../web/dist/assets/swift-Dg5xB15N.js' assert { type: 'file' };
import asset29 from '../../../web/dist/assets/toml-vGWfd6FD.js' assert { type: 'file' };
import asset30 from '../../../web/dist/assets/tsx-COt5Ahok.js' assert { type: 'file' };
import asset31 from '../../../web/dist/assets/typescript-BPQ3VLAy.js' assert { type: 'file' };
import asset32 from '../../../web/dist/assets/workbox-window.prod.es5-BIl4cyR9.js' assert { type: 'file' };
import asset33 from '../../../web/dist/assets/xml-sdJ4AIDG.js' assert { type: 'file' };
import asset34 from '../../../web/dist/assets/yaml-Buea-lGh.js' assert { type: 'file' };
import asset35 from '../../../web/dist/favicon.ico' assert { type: 'file' };
import asset36 from '../../../web/dist/icon.svg' assert { type: 'file' };
import asset37 from '../../../web/dist/index.html' assert { type: 'file' };
import asset38 from '../../../web/dist/manifest.webmanifest' assert { type: 'file' };
import asset39 from '../../../web/dist/mask-icon.svg' assert { type: 'file' };
import asset40 from '../../../web/dist/maskable-icon-512x512.png' assert { type: 'file' };
import asset41 from '../../../web/dist/pwa-192x192.png' assert { type: 'file' };
import asset42 from '../../../web/dist/pwa-512x512.png' assert { type: 'file' };
import asset43 from '../../../web/dist/pwa-64x64.png' assert { type: 'file' };
import asset44 from '../../../web/dist/sw.js' assert { type: 'file' };

export interface EmbeddedWebAsset {
    path: string;
    sourcePath: string;
    mimeType: string;
}

export const embeddedAssets: EmbeddedWebAsset[] = [
    { path: '/apple-touch-icon-180x180.png', sourcePath: asset0, mimeType: 'image/png' },
    { path: '/assets/c-BIGW1oBm.js', sourcePath: asset1, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/csharp-K5feNrxe.js', sourcePath: asset2, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/css-DPfMkruS.js', sourcePath: asset3, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/diff-D97Zzqfu.js', sourcePath: asset4, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/dockerfile-BcOcwvcX.js', sourcePath: asset5, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/github-dark-DHJKELXO.js', sourcePath: asset6, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/github-light-DAi9KRSo.js', sourcePath: asset7, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/go-Dn2_MT6a.js', sourcePath: asset8, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/graphql-ChdNCCLP.js', sourcePath: asset9, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/html-GMplVEZG.js', sourcePath: asset10, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/index-CSldWD4Q.js', sourcePath: asset11, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/index-CxSTaK8w.css', sourcePath: asset12, mimeType: 'text/css; charset=utf-8' },
    { path: '/assets/ini-BEwlwnbL.js', sourcePath: asset13, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/java-CylS5w8V.js', sourcePath: asset14, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/javascript-wDzz0qaB.js', sourcePath: asset15, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/json-Cp-IABpG.js', sourcePath: asset16, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/jsx-g9-lgVsj.js', sourcePath: asset17, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/kotlin-BdnUsdx6.js', sourcePath: asset18, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/make-CHLpvVh8.js', sourcePath: asset19, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/markdown-Cvjx9yec.js', sourcePath: asset20, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/php-CDn_0X-4.js', sourcePath: asset21, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/powershell-Dpen1YoG.js', sourcePath: asset22, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/python-B6aJPvgy.js', sourcePath: asset23, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/rust-B1yitclQ.js', sourcePath: asset24, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/scss-OYdSNvt2.js', sourcePath: asset25, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/shellscript-Yzrsuije.js', sourcePath: asset26, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/sql-BLtJtn59.js', sourcePath: asset27, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/swift-Dg5xB15N.js', sourcePath: asset28, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/toml-vGWfd6FD.js', sourcePath: asset29, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/tsx-COt5Ahok.js', sourcePath: asset30, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/typescript-BPQ3VLAy.js', sourcePath: asset31, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/workbox-window.prod.es5-BIl4cyR9.js', sourcePath: asset32, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/xml-sdJ4AIDG.js', sourcePath: asset33, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/assets/yaml-Buea-lGh.js', sourcePath: asset34, mimeType: 'text/javascript; charset=utf-8' },
    { path: '/favicon.ico', sourcePath: asset35, mimeType: 'image/x-icon' },
    { path: '/icon.svg', sourcePath: asset36, mimeType: 'image/svg+xml' },
    { path: '/index.html', sourcePath: asset37, mimeType: 'text/html; charset=utf-8' },
    { path: '/manifest.webmanifest', sourcePath: asset38, mimeType: 'application/manifest+json; charset=utf-8' },
    { path: '/mask-icon.svg', sourcePath: asset39, mimeType: 'image/svg+xml' },
    { path: '/maskable-icon-512x512.png', sourcePath: asset40, mimeType: 'image/png' },
    { path: '/pwa-192x192.png', sourcePath: asset41, mimeType: 'image/png' },
    { path: '/pwa-512x512.png', sourcePath: asset42, mimeType: 'image/png' },
    { path: '/pwa-64x64.png', sourcePath: asset43, mimeType: 'image/png' },
    { path: '/sw.js', sourcePath: asset44, mimeType: 'text/javascript; charset=utf-8' },
];
